# Generated by Django 4.0.2 on 2022-02-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default='23-02-2022', verbose_name='date joined'),
        ),
    ]
