# Generated by Django 4.0.2 on 2022-02-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(default='23-02-2022', verbose_name='birth date'),
        ),
    ]
