# Generated by Django 4.0.2 on 2022-02-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(verbose_name='date joined'),
        ),
    ]
